//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_GeneralLedger
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public int VoucherNo { get; set; }
        public Nullable<int> VoucherType { get; set; }
        public string VoucherName { get; set; }
        public Nullable<int> AccountCode { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public string Description { get; set; }
        public string Narration { get; set; }
        public string Reference { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
