//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_VoucherList
    {
        public int Id { get; set; }
        public int VoucherNo { get; set; }
        public int VoucherType { get; set; }
        public string VoucherName { get; set; }
        public int CashOfAccountType { get; set; }
        public string Payable { get; set; }
        public string Note { get; set; }
        public int AccountCode { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Amount { get; set; }
    }
}
