//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountsEntities : DbContext
    {
        public AccountsEntities()
            : base("name=AccountsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Acc_Cash> Acc_Cash { get; set; }
        public virtual DbSet<Acc_Chart> Acc_Chart { get; set; }
        public virtual DbSet<Acc_GeneralLedger> Acc_GeneralLedger { get; set; }
        public virtual DbSet<Acc_Group> Acc_Group { get; set; }
        public virtual DbSet<Acc_Type> Acc_Type { get; set; }
        public virtual DbSet<Acc_Voucher> Acc_Voucher { get; set; }
        public virtual DbSet<Acc_VoucherList> Acc_VoucherList { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Loan_Base_t> Loan_Base_t { get; set; }
        public virtual DbSet<Loan_ReceivePaymentHistory> Loan_ReceivePaymentHistory { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
