//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_ReceivePaymentHistory
    {
        public int Id { get; set; }
        public int LoanBaseId { get; set; }
        public Nullable<decimal> CashIn { get; set; }
        public Nullable<decimal> CashOut { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
