//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_Base_t
    {
        public int Id { get; set; }
        public string LoanInformation { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> NetPayable { get; set; }
    }
}
